# Generated by Django 3.1.1 on 2020-10-13 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cour',
            name='image',
        ),
        migrations.RemoveField(
            model_name='exercice',
            name='image',
        ),
        migrations.AddField(
            model_name='cour',
            name='partie',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
