# Generated by Django 3.1.1 on 2020-10-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_auto_20201013_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Présence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('le_nom_du_la_personne_qui_ecrit', models.CharField(max_length=200)),
                ('le_nom_du_User', models.CharField(max_length=200)),
                ('présence', models.BooleanField(blank=True, default=True, null=True)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
    ]
