# Generated by Django 3.1.1 on 2020-10-18 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0003_présence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='présence',
            old_name='le_nom_du_User',
            new_name='heure',
        ),
        migrations.RenameField(
            model_name='présence',
            old_name='le_nom_du_la_personne_qui_ecrit',
            new_name='le_nom_du_la_personne_qui_écrit',
        ),
        migrations.AddField(
            model_name='présence',
            name='le_nom_du_éléve',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
