# Generated by Django 3.1.1 on 2020-10-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0004_auto_20201018_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
