# Generated by Django 3.1.1 on 2020-10-18 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0005_exercice_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corrigé',
            old_name='Corrigé',
            new_name='correction_name',
        ),
        migrations.RemoveField(
            model_name='exercice',
            name='image',
        ),
    ]
