# Generated by Django 3.1.1 on 2020-10-18 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0006_auto_20201018_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='présence',
            name='matiére',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
