# Generated by Django 3.1.1 on 2020-10-21 18:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0014_auto_20201018_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='emploi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=2000)),
                ('téléphone', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='heure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Matiére',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiére', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='classe',
            name='Lien',
        ),
        migrations.RemoveField(
            model_name='corrigé',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cour',
            name='name',
        ),
        migrations.RemoveField(
            model_name='exercice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='présence',
            name='le_nom_du_la_personne_qui_écrit',
        ),
        migrations.RemoveField(
            model_name='présence',
            name='le_nom_du_éléve',
        ),
        migrations.AddField(
            model_name='classe',
            name='lien',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='présence',
            name='les_éléves_qui_vont_étre_marqué',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('matiére', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='download.matiére')),
            ],
        ),
        migrations.CreateModel(
            name='Live_ended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cour', models.CharField(max_length=100)),
                ('partie', models.CharField(max_length=100)),
                ('live', models.FileField(upload_to='')),
                ('matiére', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='download.matiére')),
                ('professeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='download.professeur')),
            ],
        ),
        migrations.AddField(
            model_name='corrigé',
            name='professeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='download.professeur'),
        ),
        migrations.AddField(
            model_name='cour',
            name='professeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='download.professeur'),
        ),
        migrations.AddField(
            model_name='exercice',
            name='professeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='download.professeur'),
        ),
        migrations.AddField(
            model_name='présence',
            name='combien_du_heure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='download.emploi'),
        ),
        migrations.AddField(
            model_name='présence',
            name='marqué_la_présence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='download.etudiant'),
        ),
        migrations.AddField(
            model_name='présence',
            name='professeur_qui_a_approuvé',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='download.professeur'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='matiére',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='download.matiére'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='professeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='download.professeur'),
        ),
        migrations.AlterField(
            model_name='présence',
            name='heure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='download.heure'),
        ),
        migrations.AlterField(
            model_name='présence',
            name='matiére',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='download.matiére'),
        ),
    ]
